// const serverAddress = "http://php.test/";
const serverAddress = "https://api.igc.onestudies.com/";
const displayDefaultFileOnStartup = false;
let calculationSlowdown = 100;
let numberOfCalculations = 1000;
const showCpuUsageWarning = false;
const curveAllowedDeviation = false;
const circleMaxGap = 0.02; // maximum distance between start- and endPoint
const circleRadiusMinFactor = 1.9;
